lib/Controller/top_loading_controller.dart
lib/Service/Firebase/Authentication/authentication_service.dart
pubspec.yaml

[TSK3-12] FirebaseAuthによる匿名ログイン

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
ios/Podfile
ios/Runner.xcodeproj/project.pbxproj
ios/Runner/Info.plist
lib/Service/Package/PermissionHandler/permission_handler_service.dart
pubspec.yaml

Serviceとして端末のパーミッションへのリクエストを行えるように追加
ネイティブコードは最小限のため、必要に応じて追記の必要あり

[TSK3-16] PermissionHandlerをService化

---

lib/View/Component/Parts/Profile/profile_detail_cell.dart
lib/View/Component/Parts/user_image_circle.dart
lib/View/Profile/profile_top_view.dart

ユーザーアイコン表示用の領域とプロフィールタブに使う機能別セルの作成

[TSK5-8]コンポーネント作成 profile

---

ios/Flutter/Release.xcconfig
ios/Podfile
lib/Constants/strings.dart
lib/Service/Package/LocalAuth/local_auth_service.dart
pubspec.yaml

LocalAuthServiceとして主に生体認証を通過させるサービスを実装しました

[TSK3-15] Local認証サービスの実装

---

assets/color/colors.xml
lib/Constants/strings.dart
lib/View/Component/CustomWidget/custom_appbar.dart
lib/View/Component/Parts/health_check_button.dart
lib/View/Home/home_view.dart

[TSK7-21] アプリ全体に使用するコンポーネントの作成

---

lib/Model/Entiry/contact_user.dart
lib/Service/Package/NativeContacts/native_contacts_service.dart
pubspec.yaml

iOS Nativeの連絡先アプリから情報を受け取るサービスです

[TSK3-19] NativeContactsサービス実装

---

lib/Service/Package/PermissionHandler/permission_handler_service.dart

[TSK3-16] Nativeの設定画面を開く関数をServiceに追加

---

lib/View/Component/CustomWidget/custom_text.dart

fix: maxLineをnull許容に

---

lib/View/Component/Parts/Home/board_tile.dart
lib/View/Component/Parts/user_image_circle.dart
lib/View/Component/Parts/user_info_tile.dart

[TSK7-26] imagePathの廃止

---

lib/Model/Entiry/contact_user.dart

[TSK3-19] ContactUserモデルからimageUrlを削除

---

lib/View/Component/Parts/Chat/department_badges.dart
lib/View/Component/Parts/Chat/message_tile.dart

[TSK7-23] departmentバッジの作成 メッセージタイル修正

---

android/app/src/main/AndroidManifest.xml
ios/Runner/Info.plist
lib/Service/Package/ImageUtils/image_utils_service.dart
pubspec.yaml

ImagePickerとImageCompressを併用し、バイナリファイルと画像Widgetを相互に扱いやすくするためのサービスです

[TSK3-22] ImageUtilsService実装

---

lib/View/Component/Parts/circle_button.dart

[TSK2-11] 共通丸型ボタンの追加

---

lib/Constants/Enum/user_role_enum.dart
lib/Model/Entiry/Account/account.dart
lib/Model/Entiry/Account/account_request.dart
lib/Model/Entiry/api_response.dart
lib/Service/Api/Account/account_api.dart
lib/Service/Api/Account/api_account.dart
lib/Service/Api/Core/api_core.dart

[TSK4-12] account Model Service Enum 追加

---

lib/View/Component/Parts/checkbox_tile.dart

[TSK2-12] チェックボックス付きタイルの追加

---

lib/View/Component/Parts/Home/board_tile.dart
lib/View/Component/Parts/user_image_circle.dart
lib/View/Component/Parts/user_info_tile.dart

[TSK7-34] Image > imageUrl

---

lib/View/Component/CustomWidget/custom_textfield.dart

[TSK5-21]CustomTextfieldの修正

---

lib/View/Component/CustomWidget/custom_textfield.dart

fix: backgroundcolorにデフォルトColors.whiteを追加

---

lib/Model/Entity/Department/department.dart
lib/Model/Entity/Doctor/doctor.dart
lib/Model/Entity/Hospital/hospital.dart
lib/Service/Api/Core/api_core.dart
lib/Service/Api/Core/endpoint.dart
lib/Service/Api/Hospital/hospital_api.dart

/hospital API 作成に基づいた
department doctor hospital Model 追加
Endpoint 追記
api_core のparameterをプライベート変数に変更(普通に動いてませんでした( ◠‿◠ ))

[TSK4-21] /hospital API 作成

---

lib/View/Component/CustomWidget/custom_textfield.dart

fix: keyboardTypeを切り替えられるように変更

---

lib/View/Component/Parts/circle_button.dart

[TSK5-23]CircleButtonにborderを追加する

---

lib/View/Component/Parts/user_image_circle.dart

[TSK7-38] user_image_circleの微修正

---

lib/Service/Api/Core/endpoint.dart
lib/Service/Api/Department/department_api.dart

department API 作成
Modelの方はhospital APIタスクの方で作成済
endpoint department 追記

[TSK4-24] /department API 作成

---

lib/View/Component/Parts/Profile/common_item_tile.dart

[TSK5-25]CommonItemTileのactionとonTap周り修正

---

lib/Service/Api/Core/api_core.dart
lib/Service/Api/Hospital/hospital_api.dart
lib/Service/Api/User/user_api.dart

doctor_api 実装時、既存のparameterの値では、うまくいかないため、
api_core自体の_urlを修正
それに伴った、各APIのparameter値を修正

[HOTFIX] parameter値の修正

---

lib/Model/Entity/Doctor/doctorRequest.dart
lib/Service/Api/Core/endpoint.dart
lib/Service/Api/Docotor/doctor_api.dart

/doctor API 作成
endpoint 追記
Doctor DoctorRequest Model 作成

[TSK4-23] /doctor API 作成

---

lib/Model/Entity/HealthCheckUp/health_checkup.dart
lib/Model/Entity/HealthCheckUp/health_checkup_request.dart
lib/Service/Api/Core/endpoint.dart
lib/Service/Api/HealthCheckup/health_checkup_api.dart

health_checkup_api 作成
endpoint 追記
Model 作成

[TSK4-22] /health_checkup API 作成

---

lib/View/Component/Parts/circle_button.dart

[TSK2-20] CircleButtonのonTap処理の修正

---

android/app/src/main/AndroidManifest.xml
ios/Runner.xcodeproj/project.pbxproj
ios/Runner/Info.plist
ios/Runner/Runner.entitlements
lib/Constants/Enum/fcm_topic_enum.dart
lib/Controller/top_loading_controller.dart
lib/Service/Firebase/CloudMessaging/cloud_messaging_service.dart
pubspec.yaml

[TSK3-34] CloudMessaging Service実装

---

lib/Model/Entity/HealthCheckUp/health_checkup.dart
lib/Model/Entity/HealthCheckUp/health_checkup_request.dart
lib/Model/Entity/User/user.dart
lib/Model/Entity/User/user_request.dart

日付の値をStringからDatetime型に
それに伴ってtoJson fromJsonの修正

[HOTFIX] User Health_checkup Model 修正

---

lib/View/Home/home_view.dart
pubspec.yaml

[TSK3-26] HomeViewの実装

---

lib/Route/router.dart
lib/Route/routes.dart
lib/View/HealthCheckup/Results/health_checkup_results_view.dart
lib/View/HealthCheckup/health_checkup_top_view.dart

[TSK7-43] 検診結果画面の作成

---

lib/Model/custom_picker.dart
lib/View/Component/CustomWidget/custom_drum_roll.dart

CustomDrumRollのHotfixをリファクタリングしました
・モードの切り替えにEnumを利用するように変更
・日付・時刻ともにCustomPickerを利用する形に変更
・変数名の改定とNull引数の活用による最適化

[REFACTOR] CustomDrumRollの最適化

---

lib/Model/custom_picker.dart
lib/View/Component/CustomWidget/custom_drum_roll.dart

CustomPickerファイル作成
CustomDrumRolのタイプを(年・月・日)と(時・分)、(時・分(15分刻み))の3パターンで切り替えられるように変更

[TSK5-24]CustomDrumRollのshowTime12hPickerをshowPicker(秒無し,15or30m刻み)に変更

---

lib/Constants/Enum/progress_view_enum.dart
lib/Route/router.dart
lib/Route/routes.dart
lib/View/Component/Pages/progress_view.dart

[TSK7-42]〇〇中Viewの作成

---

lib/Model/Entity/Chat/chat.dart
lib/Model/Entity/Chat/chat_doctor.dart
lib/Model/Entity/Chat/chat_user.dart
lib/Model/Entity/Chat/message.dart
lib/Service/Api/Chat/chat_api.dart
lib/Service/Api/Core/endpoint.dart

[TSK4-25] /chat API 作成

---

lib/View/Component/Parts/Profile/common_item_tile.dart

add: 引数boxDecoration追加

---

lib/Model/Entity/Medicine/medicine.dart
lib/Model/Entity/Medicine/medicine_request.dart
lib/Service/Api/Core/endpoint.dart
lib/Service/Api/Medicine/medicine_api.dart

/medicine API 作成
に伴ったmedicine medicineRequest Model 作成

[TSK4-27] /medicine API 作成

---

lib/View/Component/CustomWidget/custom_dropdown.dart

[TSK5-30]CustomDropdown作成

---

lib/View/Component/CustomWidget/custom_scaffold.dart

resizeToAvoidBottomInset追加
bodyはrequiredに変更

[HOTFIX] [TSK3-42] CustomScaffoldのパラメータ修正

---

lib/View/Component/CustomWidget/custom_scaffold.dart

[HOTFIX] FocusNodeを受け取れるように変更

---

lib/Model/custom_picker.dart
lib/View/Component/CustomWidget/custom_drum_roll.dart
lib/View/Profile/Medicine/medicine_setting_view.dart
lib/View/Profile/physical_infomation_view.dart

・onConfirmで値を引き出せるように変更
・日付はshowDatePickerで扱うように変更

[HOTFIX] [TSK3-45] CustomDrumRollからデータを引き出しできるように修正

---

lib/View/Profile/Medicine/medicine_setting_view.dart
lib/View/Profile/Medicine/medicine_view.dart

・GestureDetector(Icon)をIconButtonに変更
・CustomDialogのtitleとbodyTextをStringsに変更
・DropdownButtonFormFieldをCustomDropdownに変更
・CustomDrumRollの引数にsplitMinuteを設定
・繰り返し設定ボタンの表示を'繰り返し: 未設定’から’毎〇曜日’に変更
・Modalに決定ボタンを追加、titleとボタンの位置調整

[TSK5-33]View修正 - MyおくすりView

---

lib/View/Component/CustomWidget/custom_scaffold.dart

[TSK7-56] resizeToAvoidBottomInsetをnull許容に

---

assets/color/colors.xml
lib/Route/router.dart
lib/Route/routes.dart
lib/View/Profile/physical_infomation_view.dart
lib/View/Profile/user_information.dart

[TSK2-17] View作成 - プロフィール - ユーザー設定View

---

lib/Service/Package/Location/location_service.dart

LocationServiceの追加実装
CreateViewマージ後再度修正

[TSK3-46] 住所文字列から緯度経度を返すサービスを配置

---

lib/Route/router.dart
lib/Route/routes.dart
lib/View/Component/Parts/blinking_widget.dart
lib/View/emergency_view.dart

・Route定義（各ViewともRootレベルでの定義）
・ユニコーン要請画面
・BlinkingWidget Component実装

[TSK3-39] ユニコーン要請画面 実装

---

lib/Model/Entity/Disease/disease.dart
lib/Service/Api/Core/endpoint.dart
lib/Service/Api/Disease/disease_api.dart

/disease API 作成
endpoint Model 作成

[TSK4-30] /disease API 作成

---

lib/Constants/Enum/day_of_week_enum.dart
lib/Model/Entity/Medicine/medicine_request.dart
lib/Model/Entity/Medicine/reminder.dart
lib/Model/Entity/Medicine/reminder_request.dart
lib/Service/Api/Medicine/medicine_api.dart

Medicine API 仕様変更により修正
reminder reminder_request Model 追加 dayOfWeekEnum 追加

[TSK4-27] Medicine API 修正

---

lib/View/Component/CustomWidget/custom_scaffold.dart
lib/View/Profile/Medicine/medicine_setting_view.dart

[HOTFIX][TSK7-57] resizeToAvoidBottomInsetの削除

---

lib/Service/Package/Location/location_service.dart

[TSK3-55] 住所から緯度経度を取得するサービスの返り値の型をGoogleMapのLatLngに変更

---

lib/Model/Entity/Chat/chat_request.dart
lib/Model/Entity/Chat/chat_response.dart
lib/Model/Entity/Chat/message_request.dart
lib/Model/Entity/Chat/message_response.dart
lib/Service/Api/Chat/chat_api.dart

/chat API 実装に伴うModel の不備修正
ChatResponse ChatRequest Model 追加

[HOTFIX] /chat API 修正

---

lib/Service/Api/HealthCheckup/health_checkup_api.dart
lib/Service/Api/User/user_api.dart

Health_check で行っていたことをEndpointの関係でuser_apiに移植

[TSK4-33] /user(Health_checkup) APi 追記

---

lib/Service/Api/Account/account_api.dart

[TSK4-38] /account API PUT 作成

---

lib/Controller/Profile/Medicine/medicine_controller.dart
lib/Model/Entity/Medicine/medicine.dart
lib/Model/Entity/Medicine/reminder.dart
lib/Route/router.dart
lib/View/Profile/Medicine/medicine_setting_view.dart
lib/View/Profile/Medicine/medicine_view.dart

- medicine_controller.dart作成
- medicine_view.dart修正
- ProfileMedicineSettingRouteに引数$extra追加

[TSK5-39]MedicineView - Controller実装

---

lib/Model/Entity/Medicine/medicine.dart
lib/Model/Entity/Medicine/medicine_request.dart

medicine medicine_request Model に dosage値 を追加

[HOTFIX][TSK4-42] medicine Model 修正

---

lib/Service/Firebase/CloudStorage/cloud_storage_service.dart
lib/Service/Package/ImageUtils/image_utils_service.dart
lib/firebase_options.dart
pubspec.yaml

CloudStorageに各画像をアップロードするためのService実装
合わせてImageUtilsServiceも修正

[TSK3-58] Cloud Storage Service実装

---

lib/View/bottom_navigation_bar_view.dart

長い時間のかかる処理で、ユーザーからのInputを防ぐプロテクターの実装
使い方はNotionへ

[HOTFIX] [TSK3-60] プロテクターローディング実装

---

lib/Controller/Chat/Doctor/Information/doctor_information_controller.dart
lib/Model/Data/Doctor/Information/doctor_information_data.dart
lib/View/Chat/Doctor/Information/doctor_information_view.dart

[TSK7-79] 医師情報画面 Controllerの実装

---

lib/Constants/strings.dart
lib/Controller/Profile/AppInformation/app_information_controller.dart
lib/Route/router.dart
lib/Route/routes.dart
lib/Service/Package/SystemInfo/system_info_service.dart
lib/View/Profile/AppInformation/app_information_view.dart
lib/View/Profile/AppInformation/license_view.dart
lib/View/Profile/Medicine/medicine_view.dart
pubspec.yaml

- app_information_controller.dart作成
- app_information_view.dart修正

[TSK5-43]AppInformationView - Controller実装

---

lib/Constants/strings.dart
lib/Controller/Profile/ChronicDisease/chronic_disease_controller.dart
lib/Controller/Profile/Medicine/medicine_setting_controller.dart

- validateFieldに薬の量に101以上の値を、1回の服用量に薬の量よりも大きい値を登録できないように処理追加
- Stringsにvalidateに使うテキストを追加

[HOTFIX][TSK5-48]medicine_settingのvalidateを追加

---

android/app/src/main/AndroidManifest.xml
ios/Runner/Info.plist
lib/Service/Package/SpeechToText/speech_to_text_service.dart
pubspec.yaml

AI検診に必要な文字起こしを行うServiceの実装をしました

[TSK7-86] Speech To Text Serviceの実装

---

lib/Controller/Chat/Ai/TextChat/ai_text_chat_controller.dart
lib/Model/Entity/ChatGPT/chatgpt_response.dart
lib/View/Chat/Ai/TextChat/ai_text_chat_view.dart
lib/View/Component/Parts/Chat/message_tile.dart

・AIチャットで使用するControllerとそれに伴うViewの修正

[TSK7-82] AIチャット画面 コントローラー実装

---

lib/Constants/Enum/stun_server_enum.dart
lib/Model/Entity/AppConfig/app_config.dart
lib/Model/Entity/User/user_notification.dart
lib/Service/Api/Call/call_api.dart
lib/Service/Api/Doctor/doctor_api.dart
lib/Service/Api/User/user_api.dart

/user/{userID}/notification GET POST PUT処理 追加
/doctor/{doctorID}/calls GET 追加
app_config Model stunServerType 値　追加
/calls GET 返り値 List<call>型に修正

[TSK4-43] multiTasks 各API追加

---

lib/Controller/Profile/Medicine/medicine_setting_controller.dart
lib/View/Profile/Medicine/medicine_setting_view.dart

putMedicine()、postMedicine()の修正
保存ボタンの処理修正

[TSK5-49]MedicineSettingController 改修

---

lib/Controller/Chat/Doctor/TextChat/doctor_text_chat_controller.dart
lib/Model/Entity/api_response.dart
lib/View/Chat/Doctor/TextChat/doctor_text_chat_view.dart
lib/View/Component/Parts/Chat/message_tile.dart

・審査対策用にメッセージの削除と通報機能を実装しました
・APIのレスポンスのdataがnullのときにも対応できるように

[HOTFIX][TSK7-89] メッセージに削除&通報機能を追加

---

lib/View/Component/CustomWidget/custom_dialog.dart
lib/View/Profile/ChronicDisease/chronic_disease_view.dart
lib/View/Profile/FamilyEmail/family_email_register_view.dart
lib/View/Profile/Medicine/medicine_setting_view.dart

表示するボタンの数を指定できるように変更
各ボタンのテキストとonTap時の挙動をそれぞれもらえるように変更

[HOTFIX][TSK5-50]CustomDialog 改修

---

lib/View/Component/CustomWidget/custom_modal.dart
lib/View/Profile/Medicine/medicine_setting_view.dart

custom_modal.dart作成
medicine_setting_view.dart修正

[TSK5-52]CustomModal 作成

---

lib/Service/Firebase/Firestore/firestore_service.dart
pubspec.yaml

[TSK3-68] FirebaseFirestore Service実装

---

lib/View/Component/CustomWidget/custom_dialog.dart

- ボタンを表示しないときのbodyTextの高さを固定からnullに修正
- ボタンを表示しないときのbottom paddingを0に修正

[HOTFIX][TSK5-54]CustomDialog 改修2

---

lib/Constants/health_checkup_questions.dart
lib/Model/Entity/HealthCheckUp/health_checkup_question.dart

ProgressBarの整合性を取るためにnormalHealthCheckupの質問を一つ削除

[TSK4-48] 検診の進行度が100%なのに質問がある

---

lib/Model/Data/User/user_data.dart
lib/View/Component/Pages/Register/register_physical_info_view.dart
lib/View/Profile/profile_top_view.dart

Providerを用いてユーザー名の管理を行う
UserDataをNotifier仕様に変更
RegisterPhysicalInfoViewのTextEditingControllerをfirstNameとlastName入れ替え

[TSK5-55]ProfileTopView - ユーザー名の動的変更

---

lib/Controller/Chat/Doctor/TextChat/doctor_text_chat_controller.dart
lib/Model/Entity/Chat/message_response.dart
lib/Service/ChatGPT/chatgpt_service.dart
lib/View/Chat/Doctor/Information/doctor_information_view.dart
lib/View/Chat/Doctor/Search/doctor_search_view.dart
lib/View/Chat/Doctor/TextChat/doctor_text_chat_view.dart
lib/View/Chat/chat_top_view.dart

・チャットトップ、医師情報画面、医師検索画面で医師の画像が表示されるように
・AIチャットからの返答トークン数を600に引き上げ
・メッセージ送信時にから必ずエラートーストが出る現象を解消
・チャット画面にチャットサポート時間を明記
- [https://www.notion.so/5eb3b2157e6c453c9556022bfe04fdda](https://www.notion.so/5eb3b2157e6c453c9556022bfe04fdda?pvs=21)

[TSK7-102] チャットタブのリファクタ①

---

lib/Controller/Profile/Medicine/medicine_setting_controller.dart
pubspec.yaml

collection.dartを追加
変更がないときはput処理を行わないように修正

[TSK5-57]MedicineSettingController修正

---

lib/Controller/Profile/FamilyEmail/family_email_register_controller.dart

[TSK5-59]FamilyEmailRegisterController修正

---

lib/Controller/Component/Pages/Register/register_address_info_controller.dart
lib/Controller/Component/Pages/Register/register_physical_info_controller.dart
lib/Controller/Component/Pages/Register/register_user_info_controller.dart
lib/Controller/top_loading_controller.dart
lib/Model/Entity/User/user.dart
lib/Model/Entity/User/user_request.dart
lib/View/Component/CustomWidget/custom_button.dart
lib/View/Component/Pages/Register/register_address_info_view.dart
lib/View/Component/Pages/Register/register_physical_info_view.dart
lib/View/Component/Pages/Register/register_user_info_view.dart
lib/View/Component/Parts/google_map_viewer.dart

- 変更がないときにボタンを押してもput処理が走らないようにする
- 誕生日のmaxDate修正
- imageUrlでの画像表示修正
- AppBar表示
- GestureDetectorをCustomButtonに変更
- GoogleMapViewerでのエラー落ち回避
- CustomButtonのfontSizeを変更できるようにする

[TSK5-58]RegisterView - リファクタ

---

lib/Controller/Profile/profile_top_controller.dart
lib/Controller/top_loading_controller.dart

- profile_top_controller.dartからtopic初回購読の処理を削除
- top_loading_controller.dartにtopic初回購読の処理を追加

[TSK5-60]Topicの初回購読タイミング変更

---

lib/View/Component/Parts/Home/receive_call_cell.dart

[TSK5-61]receive_call_cell 作成

---

lib/Constants/strings.dart
lib/Controller/Component/Pages/Register/Progress/progress_controller.dart
lib/Controller/HealthCheckup/Results/health_checkup_results_controller.dart
lib/Controller/HealthCheckup/health_checkup_top_contoller.dart
lib/Controller/HealthCheckup/normal_checkup_controller.dart
lib/Controller/top_loading_controller.dart
lib/Model/Data/HealthCheckup/health_checkup_data.dart
lib/Service/Api/HealthCheckup/health_checkup_api.dart
lib/Service/Api/User/user_api.dart
lib/Service/Package/UrlLauncher/url_launcher_service.dart
lib/View/Component/CustomWidget/custom_scaffold.dart
lib/View/HealthCheckup/Checkup/normal_checkup_view.dart
lib/View/HealthCheckup/Results/health_checkup_results_view.dart
lib/View/HealthCheckup/health_checkup_top_view.dart

・検診タブにある不具合＆バグへの修正を行いました詳しくはNotionを見ればわかります

[TSK7-103] 検診タブのリファクタ①

---

lib/View/Home/home_view.dart

コンポーネント化されたReceiveCallCellをHomeViewで利用するように変更

[TSK3-77] ReceiveCallCellの導入

---

lib/View/Component/Parts/Profile/call_reservation_tile.dart

[TSK5-65]通話予約情報タイル 作成

---

lib/Controller/Profile/profile_top_controller.dart

[TSK5-63]Profile - お問い合わせ 実装

---

lib/Controller/Home/home_controller.dart
lib/Model/Cache/Hospital/hospital_news_cache.dart
lib/Model/Entity/Hospital/hospital_news.dart
lib/Service/Api/Hospital/hospital_api.dart
lib/View/Component/Parts/Home/board_tile.dart
lib/View/Home/home_view.dart

HospitalNewsをAPIから取得して、HomeViewに表示します。

[TSK3-72] HomeView - HospitalNews機能 実装

---

lib/Constants/strings.dart
lib/Controller/Profile/CallReservation/call_reservation_controller.dart
lib/Controller/Profile/profile_top_controller.dart
lib/Model/Entity/Call/call_reservation.dart
lib/Route/router.dart
lib/Route/routes.dart
lib/Service/Api/User/user_api.dart
lib/View/Profile/CallReservation/call_reservation_view.dart

- call_reservation_view.dart作成
- call_reservation_controller.dart作成
- call_reservation.dart作成
- route追加
- user_api.dart編集

[TSK5-64]通話予約view,controller 作成

---

lib/Constants/strings.dart
lib/Controller/Profile/profile_top_controller.dart

[TSK3-79] 生体認証非対応の端末でのセキュリティを修正

---

lib/Controller/Component/Pages/Register/register_physical_info_controller.dart
lib/View/Component/CustomWidget/custom_drum_roll.dart
lib/View/Component/Pages/Register/register_physical_info_view.dart

[TSK3-80] ユーザー登録時に生年月日から当日を除外

---

lib/Controller/Profile/ChronicDisease/disease_search_controller.dart
lib/Route/router.dart
lib/Route/routes.dart
lib/Service/Api/User/user_api.dart
lib/View/Chat/chat_top_view.dart
lib/View/Component/Parts/image_banner.dart
lib/View/Profile/ChronicDisease/chronic_disease_view.dart

- image_banner.dart作成
- chronic_disease_view.dart修正
- chat_top_view.dart修正
- route追加

[TSK5-68]ImageBanner作成

---

lib/Controller/Profile/AppInformation/app_information_controller.dart
lib/View/Component/Parts/Profile/common_item_tile.dart
lib/View/Profile/AppInformation/app_information_view.dart

[TSK4-60] 退会機能の追加

---

lib/Constants/strings.dart
lib/Controller/Profile/Medicine/medicine_setting_controller.dart
lib/View/Profile/Medicine/medicine_setting_view.dart
lib/View/Profile/Medicine/medicine_view.dart

- おくすりリマインダー 重複登録の防止
- MyおくすりView ダミーデータ差し替え

[TSK5-76]おくすりview refactor

---

lib/Constants/Enum/health_checkup_result_enum.dart
lib/Controller/HealthCheckup/health_checkup_top_contoller.dart
lib/View/HealthCheckup/health_checkup_top_view.dart

しきい値に関してはnotionに詳細
https://www.notion.so/b7f4df384a2042528bd37b73601aa0af?pvs=4

[TSK4-61] 検診結果 しきい値の修正

---

lib/Controller/Profile/AppInformation/app_information_controller.dart
lib/Controller/sign_out_controller.dart
lib/Route/router.dart
lib/Route/routes.dart
lib/View/Home/home_view.dart
lib/View/Profile/AppInformation/app_information_view.dart
lib/View/sign_out_view.dart

[TSK3-88] 起動不可問題とSighOutの仮対応

---

lib/Controller/top_loading_controller.dart
lib/Model/Data/AppConfig/app_config_data.dart
lib/Model/Entity/AppConfig/app_config.dart
lib/Service/Api/AppConfig/app_config_api.dart

demoModeをサーバーから取得できるようになりました
合わせてシングルトンDataModelの調整

[TSK3-89] AppConfigにdemoModeフラグを追加

---

lib/Constants/strings.dart
lib/View/Home/home_view.dart
lib/View/top_loading_view.dart

TopLoadingに注意書きを追加
HomeViewの病院お知らせが取得できない場合のView調整
Notionスクショあり

[TSK3-92] [TSK3-91] リジェクト対応 - シミュレーションである旨を主張

---

lib/View/bottom_navigation_bar_view.dart

[TSK3-95] ユーザー画像を表示するウィジェットを追加し、プロフィールタブのアイコンを更新

---

lib/View/Profile/LocalAuth/local_auth_view.dart

[TSK5-74]LocalAuthView　改修
